name: dash_router_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/dash_router
  - packages/dash_router_annotations
  - packages/dash_router_generator
  - packages/dash_router_cli
  - example

dev_dependencies:
  melos: ^7.0.0

melos:
  useRootAsPackage: true
